export const TYPES = {
  '7z': 'Archive',
  aac: 'Audio',
  avi: 'Video',
  bmp: 'Image',
  doc: 'Word',
  docx: 'Word',
  flv: 'Video',
  jpeg: 'Image',
  jpg: 'Image',
  js: 'Code',
  mov: 'Video',
  mp3: 'Audio',
  mp4: 'Video',
  ogg: 'Audio',
  pdf: 'PDF',
  png: 'Image',
  ppt: 'PowerPoint',
  pptx: 'PowerPoint',
  rar: 'Archive',
  txt: 'Text',
  wav: 'Audio',
  wmv: 'Video',
  xls: 'Excel',
  xlsx: 'Excel',
  zip: 'Archive',
}
